"""Update table plants

Revision ID: 01e097eb1794
Revises: cc60ac065a43
Create Date: 2021-05-19 15:57:47.165012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01e097eb1794'
down_revision = 'cc60ac065a43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('temperature', sa.String(), nullable=True))
    op.add_column('plant', sa.Column('light', sa.String(), nullable=True))
    op.add_column('plant', sa.Column('humidity', sa.String(), nullable=True))
    op.add_column('plant', sa.Column('wind', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plant', 'wind')
    op.drop_column('plant', 'humidity')
    op.drop_column('plant', 'light')
    op.drop_column('plant', 'temperature')
    # ### end Alembic commands ###
