"""Update database

Revision ID: a7f812e50821
Revises: 9cdabe1d10ed
Create Date: 2021-07-05 15:19:10.898993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7f812e50821'
down_revision = '9cdabe1d10ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('reminder_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plant', 'reminder_time')
    # ### end Alembic commands ###
