"""Add user_plant_model, store_plant, store model

Revision ID: cc60ac065a43
Revises: dc290b4e9dea
Create Date: 2021-05-14 15:11:50.406574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc60ac065a43'
down_revision = 'dc290b4e9dea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_id'), 'store', ['id'], unique=False)
    op.create_index(op.f('ix_store_name'), 'store', ['name'], unique=False)
    op.create_table('storeplant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storeplant_id'), 'storeplant', ['id'], unique=False)
    op.create_table('userplant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userplant_id'), 'userplant', ['id'], unique=False)
    op.add_column('plant', sa.Column('image', sa.String(), nullable=True))
    op.drop_index('ix_plant_description', table_name='plant')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_plant_description', 'plant', ['description'], unique=False)
    op.drop_column('plant', 'image')
    op.drop_index(op.f('ix_userplant_id'), table_name='userplant')
    op.drop_table('userplant')
    op.drop_index(op.f('ix_storeplant_id'), table_name='storeplant')
    op.drop_table('storeplant')
    op.drop_index(op.f('ix_store_name'), table_name='store')
    op.drop_index(op.f('ix_store_id'), table_name='store')
    op.drop_table('store')
    # ### end Alembic commands ###
