"""Add store table

Revision ID: fbd6672b4310
Revises: 01e097eb1794
Create Date: 2021-05-19 16:17:50.920608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbd6672b4310'
down_revision = '01e097eb1794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storeplant', sa.Column('store_id', sa.Integer(), nullable=True))
    op.add_column('storeplant', sa.Column('plant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'storeplant', 'store', ['store_id'], ['id'])
    op.create_foreign_key(None, 'storeplant', 'plant', ['plant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'storeplant', type_='foreignkey')
    op.drop_constraint(None, 'storeplant', type_='foreignkey')
    op.drop_column('storeplant', 'plant_id')
    op.drop_column('storeplant', 'store_id')
    # ### end Alembic commands ###
